name: CI

on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.0

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '2.7'
          - '3.7'
          - '3.8'
          - '3.9.0-rc.1 - 3.9'

    steps:
      - uses: actions/checkout@v2
        with:
          # Make setuptools_scm able to guess the version.
          # actions/checkout#249
          fetch-depth: 0

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Ensure pip is up to date
        run: |
          python -m pip install --upgrade pip

      - name: Test
        run: |
          python -m pip install tox
          tox -e py -- --cov-report=xml

      - uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true

  release:
    needs:
      - lint
      - test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: Ensure pip is up to date
        run: |
          python -m pip install --upgrade pip

      - name: Build
        run: |
          python -m pip install pep517
          python -m pep517.build .

      - name: Publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python -m pip install twine
          twine upload dist/*

      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
